version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - ./docker/data/postgres/data:/var/lib/postgresql/data
      - ./docker/data/postgres/backups:/postgresql_backups
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
