---
- name: Print os facts
  hosts: all
#  gather_facts: false
  tasks:
    - name: Ping
      ping:
    - name: Print OS
      debug:
        msg: "{{ ansible_distribution }}"
    - name: Print fact
      debug:
        msg: "{{ some_fact }}"