---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java 11 vars
      set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ java_oracle_jdk_package }}"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        mode: "644"
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Ensure installation dir exists
      file:
        state: directory
        path: "{{ java_home }}"
        mode: "644"
      tags: java
    - name: Extract java in the installation directory
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [ --strip-components=1 ]
        creates: "{{ java_home }}/bin/java"
        mode: "644"
      tags:
        - java
    - name: Export environment variables
      template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
        mode: "644"
      tags: java
- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - name: Upload tar.gz Elasticsearch from remote URL
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        mode: "0755"
        timeout: 60
        force: true
        validate_certs: false
      register: get_elastic
      until: get_elastic is succeeded
      tags: elastic
    - name: Create directrory for Elasticsearch
      file:
        state: directory
        path: "{{ elastic_home }}"
        mode: "644"
      tags: elastic
    - name: Extract Elasticsearch in the installation directory
      unarchive:
        copy: false
        src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "{{ elastic_home }}"
        extra_opts: [ --strip-components=1 ]
        creates: "{{ elastic_home }}/bin/elasticsearch"
        mode: "644"
      tags:
        - elastic
    - name: Set environment Elastic
      template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
        mode: "644"
      tags: elastic
    - name: Set config for Elastic
      template:
        src: templates/elasticsearch.yml.j2
        dest: "{{ elastic_home }}/config/elasticsearch.yml"
        mode: "644"
      tags: kibana
- name: Install Kibana
  hosts: kibana
  tasks:
    - name: Upload tar.gz Kibana from remote URL
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        mode: "0755"
        timeout: 60
        force: true
        validate_certs: false
      register: get_kibana
      until: get_kibana is succeeded
      tags: kibana
    - name: Create directrory for Kibana
      file:
        state: directory
        path: "{{ kibana_home }}"
        mode: "644"
      tags: kibana
    - name: Extract Kibana in the installation directory
      unarchive:
        copy: false
        src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        dest: "{{ kibana_home }}"
        extra_opts: [ --strip-components=1 ]
        creates: "{{ kibana_home }}/bin/kibana"
        mode: "644"
      tags:
        - kibana
    - name: Set environment Kibana
      template:
        src: templates/kibana.sh.j2
        dest: /etc/profile.d/kibana.sh
        mode: "644"
      tags: kibana
    - name: Set config for Kibana
      template:
        src: templates/kibana.yml.j2
        dest: "{{ kibana_home }}/config/kibana.yml"
        mode: "644"
      tags: kibana
